name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy via SFTP
        run: |
          sudo apt-get install -y lftp
          lftp -c "
            set sftp:auto-confirm yes;
            set net:timeout 30;
            set net:max-retries 3;
            open sftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_SERVER }}:22;
            mirror --reverse --delete --verbose ./dist/ /public_html/;
          "